# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        mentor_db_provider:
            entity:
                class:    MentorBundle\Entity\User
                property: username

    encoders:
        MentorBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: ~

            guard:
                authenticators:
                    - mentor.form.form_authenticator
                entry_point: mentor.form.form_authenticator

            form_login:
                login_path:           login
                check_path:           login
                csrf_token_generator: security.csrf.token_manager
                provider:             mentor_db_provider

            logout:
                path:   /logout
                target: /

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
