# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    mentor.form.form_authenticator:
        class:      MentorBundle\Security\FormAuthenticator
        arguments:  ["@security.password_encoder", "@router"]
        autowire:   true
