# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    mentor.form.form_session:
        class: MentorBundle\Form\Type\SessionType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type}

    mentor.form.form_authenticator:
        class:      MentorBundle\Security\FormAuthenticator
        arguments:  ["@security.password_encoder", "@router"]
        autowire:   true
