# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    mentor.session_class: MentorBundle\Entity\Session
    mentor.student_class: MentorBundle\Entity\Student
    mentor.path_class:    MentorBundle\Entity\Path
    mentor.project_class: MentorBundle\Entity\Project

services:
    # Forms
    mentor.form.form_session:
        class: MentorBundle\Form\Type\SessionType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type}

    # Security
    mentor.security.form_authenticator:
        class:      MentorBundle\Security\FormAuthenticator
        autowire:   true

    # Events
    mentor.doctrine.hash_password_listener:
        class: MentorBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    # Services
    mentor.total_amount_calculator:
        class: MentorBundle\Services\TotalAmountCalculator
        autowire: true

    mentor.export_excel:
        class: MentorBundle\Services\ExportExcel
        autowire: true

    mentor.export_pdf:
        class: MentorBundle\Services\ExportPDF
        autowire: true

    mentor.pagination:
        class: MentorBundle\Services\Pagination
        autowire: true

    # Repositories
    mentor.session_repository:
        class: MentorBundle\Repository\SessionRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ["%mentor.session_class%"]

    mentor.path_repository:
        class: MentorBundle\Repository\PathRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ["%mentor.path_class%"]

    mentor.project_repository:
        class: MentorBundle\Repository\ProjectRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ["%mentor.project_class%"]

    mentor.student_repository:
        class: MentorBundle\Repository\StudentRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ["%mentor.student_class%"]

    # Twig extensions
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    # Form extensions
    mentor.form.extension.help:
        class: MentorBundle\Form\Extension\HelpFormExtension
        autowire: true
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
